services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ../.env
    environment:
      PGDATA: /data/postgres
    volumes:
       - ./db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
